// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/metadata.ts";
import * as $1 from "./routes/index.tsx";

const manifest = {
  islands: {},
  routes: {
    "./routes/api/metadata.ts": $0,
    "./routes/index.tsx": $1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
